![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Crea un array de 10 ceros. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla. ¿Cuánto ocupa ahora?

## Ejercicio 2
Crea un vector que vaya del 10 al 49

Inviértelo

## Ejericio 3
Encuentra los índices del vector [1,2,0,0,4,0], cuyo valor **no sean 0**. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [18]:
import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])

list(np.nonzero(v)[0])


l = []
for i in range(len(v)):
    if v[i] != 0:
        l.append(i)
        
resultado = np.where(v != 0)
resultado[0]

array([0, 1, 4], dtype=int64)

## Ejercicio 4

En este ejercicio vamos a utilizar cosas aleatorias, por lo que comienza configurando la semilla que vas a utilizar ocn un valor fijo. Este valor da igual cuál sea, pero deberá ser siempre el mismo. Para que todos obtengamos el mismo resultado, pon una semilla de 10.

Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [35]:
np.random.seed(10)

x = np.random.randint(1, 100, size=(10, 10))

print(x)
print(np.amax(x, axis = 0))
print(np.amax(x, axis = 1))
print(np.min(x))

max_fila = []


[[10 16 65 29 90 94 30  9 74  1]
 [41 37 17 12 55 89 63 34 73 79]
 [50 52 55 78 70 14 26 14 93 87]
 [31 31 90 13 66 32 58 37 28 19]
 [94 78 23 24 95 12 29 75 89 10]
 [16 19 81 72 89 12 18 47  8 76]
 [29 34 85 97 89 45  6  5 72 89]
 [89 51 55 35 16 78 89 16  7 86]
 [23 12 13 93 97 63 58 80 43 58]
 [98 51 46 41 90 74 38  1 19 24]]
[98 78 90 97 97 94 89 80 93 89]
[94 89 93 90 95 89 97 89 97 98]
1


## Ejercicio 5
Crea un vector aleatorio de tamaño 30 y calcula su media

0.4635438936222714


## Ejercicio 6
Crea un array cuadrado de 2D, con las dimensiones que quieas, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [48]:
n = 5

z = np.zeros((n, n*2))
z[::, 0] = 1
z[::, -1] = 1
z[0, ::] = 1
z[-1, ::] = 1

z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
my_array6 = np.ones((5,5))
print("Fill with zeroes:")
my_array6[1:-1,1:-1] = 0
print(my_array6)

Fill with zeroes:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
z.shape

(5, 10)

In [55]:
n = 5

z = np.zeros((n, n*2))

for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        if i==0 or i==z.shape[0]-1 or j==0 or j==z.shape[1]-1:
            z[i][j] = 1
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 7
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

## Ejercicio 8
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [66]:
np.random.seed(10)

matrix = np.random.randint(1, 10, size=(5, 5))

matrix = (matrix - np.mean(matrix)) / np.std(matrix)

matrix

array([[ 0.13066828, -1.32120148, -0.95823404, -1.32120148, -0.95823404],
       [ 1.58253804, -1.32120148,  1.58253804,  0.85660316,  0.13066828],
       [-0.23229916, -1.32120148,  0.13066828,  0.85660316,  1.58253804],
       [-0.95823404,  1.58253804,  0.13066828, -0.95823404, -0.23229916],
       [ 0.85660316,  0.49363572, -0.23229916,  0.85660316, -0.95823404]])

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8