![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

## Ejercicio 2
Repitamos lo mismo para un array biidimensional que vaya del 0 al 9 y que sea (2 x 5). Llámalo `my_matrix`. 
1. Multiplica cada uno de los elementos de `my_matrix` por 10, en un nuevo array
2. Accede a la primera fila y al primer elemento del array
3. Accede a la última fila y al último elemento del array
4. Imprime por pantalla la primera, tercera y quita columnas. Utiliza el slicing que hemos visto

## Ejercicio 3
Repitamos lo mismo ahora para un array ndimensional del tamaño que sea. Llámalo `my_nmatrix`. 
1. Multiplica cada uno de los elementos de `my_nmatrix` por 10, en un nuevo array
2. Imprime el primer elemento de cada subarray, es decir, en el caso de una matriz tridimensional, imprime la primera matriz bidimensional que aparezca, la primera fila que tenga esa matriz bidimensional y el primer elemento de esa fila. Utiliza un bucle for para recorrer las dimensiones. Ejemplo, si tengo una matriz de 3 dimensiones, imprimiré, matriz[0], matriz[0][0], matriz[0][0][0], pero tengo que hacerlo de forma genérica, de modo que se adapte a las dimensiones de la matriz
3. Haz lo mismo que en el apartado 2, pero para los últimos elementos

## Ejercicio 4
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```


## Ejercicio 5
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 6

Crea una función que tome como argumento un array numérico (no hay que hacer ninguna comprobación, vamos a suponer que el argumento que nos pasan es un array numérico y no va a tener strings ni nada por el estilo) y compruebe si todos sus elementos son enteros o, si está formada por decimales, que todas las partes decimales sean 0. En ambos casos, la función deberá devolver una matriz con enteros.

NOTA: Si la matriz ya era de enteros, no hace falta hacer ninguna modificación, pero si la matriz tiene floats, tendremos que comprobar que todas las partes decimales sean 0 e ir guardando en una nueva matriz cada uno de estos elementos convertidos a entero (np.int32). Si detectamos alguna parte decimal distinta de 0, tendremos que imprimir un mensaje diciendo que esta matriz no es entera y devolveremos la matriz original.

## Ejercicio 7
Crea un array de 4x1. A continuación convierte el array a un 2x2

[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 8
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

## Ejercicio 9
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 10
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión? (Es decir, cuál es la forma del array. En una matriz sería ¿cuántas filas y columnas tiene?)

## Ejercicio 11

Crea una función que reciba como argumento un array y te imprima por pantalla la info que hemos sacado en el ejercicio anterior:

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?