![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Crea un array de 10 ceros. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla. ¿Cuánto ocupa ahora?

In [14]:
import numpy as np

x = np.zeros(10)
print(x)

print(x.itemsize) # Cada elemento
print(x.nbytes) # El array entero

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80


In [15]:
x[3] = 1.29
print(x)

[0.   0.   0.   1.29 0.   0.   0.   0.   0.   0.  ]


In [16]:
print(x.itemsize) # Cada elemento
print(x.nbytes) # El array entero

8
80


## Ejercicio 2
Crea un vector que vaya del 10 al 49

Inviértelo

In [6]:
x = np.arange(10, 50)
print(x)
print(x[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 3
Encuentra los índices del vector [1,2,0,0,4,0], que **no sean 0**. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [7]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

## Ejercicio 4

En este ejercicio vamos a utilizar cosas aleatorias, por lo que comienza configurando la semilla que vas a utilizar ocn un valor fijo. Este valor da igual cuál sea, pero deberá ser siempre el mismo. Para que todos obtengamos el mismo resultado, pon una semilla de 10.

Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [25]:
np.random.seed(10)

#x = np.random.random((10,10))
x = np.random.randint(1, 100, size = (10,10))
print(x)

print(x.min())
print(x.max())

[[10 16 65 29 90 94 30  9 74  1]
 [41 37 17 12 55 89 63 34 73 79]
 [50 52 55 78 70 14 26 14 93 87]
 [31 31 90 13 66 32 58 37 28 19]
 [94 78 23 24 95 12 29 75 89 10]
 [16 19 81 72 89 12 18 47  8 76]
 [29 34 85 97 89 45  6  5 72 89]
 [89 51 55 35 16 78 89 16  7 86]
 [23 12 13 93 97 63 58 80 43 58]
 [98 51 46 41 90 74 38  1 19 24]]
1
98


## Ejercicio 5
Crea un vector aleatorio de tamaño 30 y calcula su media

In [20]:
x = np.random.random(30)
m = x.mean()
print(m)

0.4635438936222714


## Ejercicio 6
Crea un array cuadrado de 2D, con las dimensiones que quieas, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [24]:
x = np.ones((10,10))
x[1:-1:, 1:-1:] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 7
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [29]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 8
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [31]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [33]:
x = np.random.randint(1, 20, (5,5))

x = (x - np.mean(x))/np.std(x)

print(x)

[[ 1.31889152 -0.82216614  1.31889152  1.53299729 -0.17984884]
 [-1.46448344  1.10478575  0.89067999  0.89067999 -0.60806038]
 [ 0.89067999 -0.17984884  1.10478575  0.03425692 -0.60806038]
 [-0.60806038 -1.03627191 -0.82216614  1.74710305 -1.67858921]
 [ 0.24836269 -0.39395461 -0.60806038 -1.03627191 -1.03627191]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [37]:
x = np.arange(11)
print(x)

y = x.copy()
y[(y > 3) & (y <= 8)] = -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [38]:
y = x.copy()
y[(y > 3) & (y <= 8)] *= -1
print(y)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# Equivalente
y[(y > 3) & (y <= 8)] = y[(y > 3) & (y <= 8)] * -1

In [ ]:
x *= -1
x = x * (-1)