![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

# 1.
my_array = np.arange(10)
print(my_array)

# 2.
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


In [4]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
print(my_array)
print(my_array[-8::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


In [13]:
# Otra solución, en dos pasos
my_array[0:3][::-1]

array1 = my_array[0:3]
array2 = array1[::-1]
print(array1)
print(array2)

[0 1 2]
[2 1 0]


In [18]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [16]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(my_matrix[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [19]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
my_matrix[:2:, :2:]

array([[1, 2],
       [6, 7]])

In [21]:
my_matrix[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [22]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
my_matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [37]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
print(my_matrix[::, ::-1])
print(my_matrix[:-1:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

In [30]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Metodo 1
mask = np.array([True, False, False, True, False])

x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [33]:
# Metodo 2
mask = x == "Loro"
print(mask)
x[mask]

[ True False False  True False]


array(['Loro', 'Loro'], dtype='<U5')

In [35]:
# Metodo 3
mask = np.where(x == "Loro")
print(mask)
x[mask]

(array([0, 3], dtype=int64),)


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [17]:
x = np.arange(20).reshape((2,5,2))
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [40]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
my_matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])