![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
print(np.__version__)

1.18.5


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llámalo `my_array`

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
x = np.full((3,3), True, dtype = bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`. Consejo: utiliza una máscara de booleanos.

In [5]:
mask = my_array % 2 == 1
print(my_array)
print(mask)
print(my_array[mask])

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [6]:
np.where(my_array % 2 == 1)

(array([1, 3, 5, 7, 9], dtype=int64),)

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [7]:
new_array = my_array.copy()

mask = new_array % 2 == 1
print(mask)

new_array[mask] = -1
print(new_array)

[False  True False  True False  True False  True False  True]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [10]:
out = np.where(my_array % 2 == 1, -1, my_array)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [19]:
print(my_array.size)

my_array.reshape((2,5))

10


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Obtén la documentación acerca de la función `concatenate`

Utiliza esa función para concatenar los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
import numpy as np
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

np.concatenate([a,b], axis = 0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Haz lo mismo con los siguientes arrays, pero esta vez horizontamente. Usa el mismo comando que en el ejercicio anterior:

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambas listas. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])