## Ejercicio 1
Importa la libreria de pandas. ¿Qué versión de la librería tienes?

In [ ]:
import pandas as pd
import numpy as np

pd.__version__

## Ejercicio 2
Lee el archivo CSV de la liga. Guarda el DataFrame en una variable llamada `df`. [Usa el método `read_csv` de `pandas`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Este método lo veremos más adelante, junto con otros muchos de lectura y escritura de datos, pero está bien que te vayas familiarizando con él:

In [2]:
df = pd.read_csv("laliga.csv", sep=',')

## Ejercicio 3
Obtén por pantalla los 4 primero registros

In [ ]:
df[0:4]

In [5]:
df.iloc[0:4]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [8]:
df.head(4)

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [14]:
df['division']

0       1
1       1
2       1
3       1
4       1
       ..
4935    1
4936    1
4937    1
4938    1
4939    1
Name: division, Length: 4940, dtype: int64

## Ejercicio 4
Obtén en un array de `numpy` todos los valores del DataFrame

In [10]:
df.values

array([[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       ...,
       [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
       [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
       [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]],
      dtype=object)

## Ejercicio 5
¿Cuáles son las columnas de `df`?

In [11]:
df.columns

Index(['Unnamed: 0', 'season', 'division', 'round', 'localTeam', 'visitorTeam',
       'localGoals', 'visitorGoals', 'date', 'timestamp'],
      dtype='object')

## Ejercicio 6
Crea un `Series` con la [población de Madrid, Galicia, Murcia y Andalucía](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a). Llámalo `poblacion`. Créalo de dos maneras diferentes.

In [15]:
poblacion = pd.Series({"Madrid": 6685471, "Galicia": 2698764, "Murcia": 1494442, "Andalucia": 8446561})
poblacion

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64

In [16]:
poblacion = pd.Series([6685471, 2698764, 1494442, 8446561], index = ["Madrid", "Galicia", "Murcia", "Andalucia"])
poblacion

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64

## Ejercicio 7
Obtén un array de `numpy` con los valores del `Series` del Ejercicio 6.

Saca también sus índices, y los valores de sus índices.

In [18]:
poblacion.values

array([6685471, 2698764, 1494442, 8446561], dtype=int64)

In [23]:
poblacion.to_numpy()

array([6685471, 2698764, 1494442, 8446561], dtype=int64)

In [20]:
print(poblacion.index)
print(poblacion.index.values)

Index(['Madrid', 'Galicia', 'Murcia', 'Andalucia'], dtype='object')
['Madrid' 'Galicia' 'Murcia' 'Andalucia']


## Ejercicio 8
1. ¿Qué población hay en el primer elemento del `Series`?
2. ¿Qué población hay en Galicia?
3. Imprime por pantalla las poblaciones de Galicia, Andalucía y las comunidades autónomas que se encuentren entre ambas (según el Series, no en el plano).
4. Comprueba con un output booleano que `Galicia` se encuentra entre los índices del `Index`.
5. Realiza los apartados 1,2,3 pero esta vez de una manera diferente, es decir, cambiando la forma de llamar a los índices).

In [29]:
# 1. 
print(poblacion[0])
print(poblacion.iloc[0])
print(poblacion.loc['Madrid'])

6685471
6685471
6685471


In [31]:
# 2.
print(poblacion['Galicia'])
print(poblacion.loc['Galicia'])

2698764
2698764


In [33]:
# 3.
print(poblacion['Galicia': 'Andalucia'])
print(poblacion.loc['Galicia': 'Andalucia'])

Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64


In [35]:
# 4.
print('Galicia' in poblacion)
print('Galicia' in poblacion.index)

True
True


## Ejercicio 9
A partir de las comunidades autónomas anteriores, crea un `Series` con [la tasa de paro](https://es.statista.com/estadisticas/941646/prevision-de-la-tasa-de-paro-por-comunidad-autonoma-espana/) en dichas comunidades autónomas.

Con la tasa de paro y las poblaciones, crea un DataFrame de pandas. Llámalo `data`.

In [37]:
paro = pd.Series({"Madrid": 9.99, "Galicia": 11.74, "Murcia": 16.08, "Andalucia": 20.8})
paro

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucia    20.80
dtype: float64

In [39]:
data = pd.DataFrame({"Poblacion": poblacion, "Tasa paro": paro})
data.head()

Poblacion  Tasa paro
Madrid       6685471       9.99
Galicia      2698764      11.74
Murcia       1494442      16.08
Andalucia    8446561      20.80

## Ejercicio 10
Imprime por pantalla la población, y la tasa de paro. Por separado

In [40]:
print(data['Poblacion'])

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
Name: Poblacion, dtype: int64


In [41]:
print(data['Tasa paro'])

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucia    20.80
Name: Tasa paro, dtype: float64


## Ejercicio 11
Crea un nuevo Data Frame (`data2`), que sea igual que `data`, pero con una nueva columna, que lleve [la superficie de las Comunidades Autónomas](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a).

In [43]:
superficie = pd.Series([8028, 29575, 11314, 87599], index = ["Madrid", "Galicia", "Murcia", "Andalucia"])
print(superficie)

Madrid        8028
Galicia      29575
Murcia       11314
Andalucia    87599
dtype: int64


In [44]:
data2 = pd.DataFrame({"Poblacion": poblacion, "Tasa paro": paro, "Superficie": superficie})
data2

Poblacion  Tasa paro  Superficie
Madrid       6685471       9.99        8028
Galicia      2698764      11.74       29575
Murcia       1494442      16.08       11314
Andalucia    8446561      20.80       87599

## Ejercicio 12
Calcula en una nueva columna la densidad de población (hab/km^2)

In [45]:
data2.columns

Index(['Poblacion', 'Tasa paro', 'Superficie'], dtype='object')

In [46]:
data2["Densidad poblacion"] = data2["Poblacion"] / data2["Superficie"]
data2

Poblacion  Tasa paro  Superficie  Densidad poblacion
Madrid       6685471       9.99        8028          832.769183
Galicia      2698764      11.74       29575           91.251530
Murcia       1494442      16.08       11314          132.087856
Andalucia    8446561      20.80       87599           96.423030